name: woocommerce_app
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  #sdk: ">=2.1.0 <3.0.0"
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6
  woocommerce_api: ^0.1.0
  rxdart: ^0.27.7
  fluttertoast: ^8.2.4
  http: any
  collection: ^1.17.2
  flutter_form_builder: ^9.1.1
  intl: ^0.19.0
  form_builder_validators: ^11.0.0
  flutter_login: ^5.0.0
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  flutter_secure_storage: ^9.0.0
  webview_flutter: ^2.8.0
  html: ^0.15.4

  #shared_preferences: ^2.2.2
 # wp_json_api: ^3.3.4
  #flutter_html: ^2.1.2
  flutter_html: ^3.0.0-alpha.9
  permission_handler: ^11.3.0
  image_picker: ^1.0.7
  file_picker: ^6.1.1
  flutter_svg: ^0.23.0+1
  gradient_like_css: ^1.0.1
  carousel_slider: ^4.2.1
  hive: ^2.2.3
  mailer: ^6.1.0
  url_launcher: ^6.2.6
  #introduction_screen: any
 # flutter_keyboard_visibility: ^6.0.0
  flutter_onboarding_slider: ^1.0.11
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.19
  foundation: ^0.0.5
  #flutter_inappwebview: ^6.0.0
 # booking_calendar: ^1.1.10
 # webview_flutter_upload: ^0.2.0
  #flutter_local_notifications: ^8.2.0
  #intro_slider: ^4.2.1
  # flutter_webview_plugin: ^0.4.0
 # progress_hud: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/cover_photo.jpg
    - images/woocom_icon.jpg
    - images/bg-esthetique.jpg
    - images/chirurgie-de-la-face.png
    - images/chirurgie-mammaire.png
    - images/chirurgie-intime.png
    - images/injections-de-botox.png
    - images/lasers-dermatologiques.png
    - images/traitement-medical-de-la-silhouette.png
    - images/chirurgie-de-la-silhouette.png
    - images/sidi-bou-said-tunisie.jpg
    - images/chirurgie-esthetique.png
    - images/slider.jpg
    - images/logo.png
    - images/logo-slider1.png
    - images/suivi.png
    - images/temoigne.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
