name: "iOS-ipa-build "

on:
	workflow_dispatch
	
jobs:
	build-ios:
	name: iOs Build
	runs-on: macos-latest
	steps:
		- uses: actions/checkout@v4
		
		- uses: subosito/flutter-action@v2
	      with:
			channel: "stable"
			architecture: x64
		- run: flutter pub get

		- run: prod repo update
		  workflow_directory: ios
		  
		- run: flutter build ios --release --no-codesign
		
		- run: mkdir Payload
		  workflow_directory: build/ios/iphoneos
		  
		- run: mv Runner.app/ Payload
		  workflow_directory: build/ios/iphoneos  
		  
		- name: Upload binaries to release
		  uses: svenstaro/upload-release-action@v2
		  with:
			repo_token: ${{ secrets.GITHUB_TOKEN }}
			file: build/ios/iphoneos/FlutterIpaExport.ipa
			tag: v1.0
			overwrite: true
			body: "This is first release"
