name: iOS-ipa-build

on:
  workflow_dispatch:

jobs:
  build-ios-and-android:
    name: iOS last Build
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
          architecture: x64

      - name: Run Flutter Doctor
        run: flutter doctor -v

      - name: Clean Flutter project
        run: flutter clean

      - name: Remove iOS build directory
        run: |
          rm -rf ios/Pods
          rm -rf ios/Podfile.lock
          rm -rf ios/Flutter/Flutter.framework

      - name: Upgrade Flutter dependencies
        run: flutter pub get

      - name: Ensure iOS platform in Podfile
        run: |
          echo "platform :ios, '12.0'" > ios/Podfile
          echo "target 'Runner' do" >> ios/Podfile
          echo "  use_frameworks!" >> ios/Podfile
          echo "  use_modular_headers!" >> ios/Podfile
          echo "  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))" >> ios/Podfile
          echo "end" >> ios/Podfile

      - name: Install CocoaPods dependencies
        run: |
          cd ios
          pod install
          cd ..

      - name: Build iOS IPA
        run: flutter build ios --release --no-codesign

      - name: Prepare iOS Payload
        run: |
          mkdir -p Payload
          mv build/ios/iphoneos/Runner.app Payload/

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: Payload/Runner.app
          tag: v1.0
          overwrite: true
          body: "This is the first release"
