name: "Build iOS"

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

jobs:
  flutter_test:
    name: Run flutter test and analyze
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.16.9'  # Assurez-vous que la version de Flutter est correcte
      - name: Get dependencies
        run: flutter pub get
      - name: Analyze code
        run: flutter analyze
      - name: Run tests
        run: flutter test

  build_ios:
    name: Build Flutter (iOS)
    needs: [flutter_test]
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.16.9'  # Assurez-vous que la version de Flutter est correcte
      - name: Get dependencies
        run: flutter pub get
      - name: Clean project
        run: flutter clean
      - name: Build iOS
        run: flutter build ios

  build_appbundle:
    name: Build Flutter (Android)
    needs: [flutter_test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.16.9'  # Assurez-vous que la version de Flutter est correcte
      - name: Get dependencies
        run: flutter pub get
      - name: Clean project
        run: flutter clean
      - name: Build app bundle
        run: flutter build appbundle
