name: Build iOS test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable' # Change to your desired Flutter version

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS
        run: flutter build ios --release --no-codesign

      - name: Archive build
        run: |
          xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner archive -archivePath ${{ github.workspace }}/build/Runner.xcarchive

      - name: Export IPA
        run: |
          xcodebuild -exportArchive -archivePath ${{ github.workspace }}/build/Runner.xcarchive -exportOptionsPlist ios/Runner/ExportOptions.plist -exportPath ${{ github.workspace }}/build/IPA

      - name: Upload IPA
        uses: actions/upload-artifact@v2
        with:
          name: ios-app
          path: build/IPA/
